output_dir = "/root/autodl-tmp/output/xxx"                         # 输出的路径
output_name = "xxx_XL_v1"                                              #输出模型的名字
pretrained_model_name_or_path = "/root/autodl-tmp/model/AnythingXL_xl.safetensors"  # 训练模型的路径
logging_dir = "/root/autodl-tmp/log/xxx"                           # 日志的路径
sample_prompts = "/root/autodl-tmp/output/xxx/prompt.txt"          #预览图的生成提示词路径
train_data_dir = "/root/autodl-tmp/data/xxx"                                  #训练集的路径
vae = "/root/autodl-tmp/model/sdxl_vae.safetensors"                                  #vae的路径
epoch = 40                                                                           #总epoch数
save_every_n_epochs = 2                                                              #多少epoch保存一次模型
bucket_no_upscale = true
bucket_reso_steps = 32
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 1e-5
learning_rate_te1 = 1e-6
learning_rate_te2 = 1e-6
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 225
max_train_epochs = 40
max_train_steps = 668
min_bucket_reso = 256
mixed_precision = "bf16"
multires_noise_discount = 0.3
multires_noise_iterations = 6
noise_offset_type = "Multires"
optimizer_type = "AdamW8bit"
prior_loss_weight = 1
resolution = "1024,1024"
sample_every_n_epochs = 1
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "bf16"
train_batch_size = 50
xformers = true
